### ISSUE TITLE
Enhancement: Make items clickable 

### ISSUE THREAD

**Issue by petersem** [plugsy/core#18]
Add a parameter in the labels that contains a link. Then make items on the dashboard clickable. 

For example, sonarr may have a link to a new window for x.x.x.x:8989
![Screenshot_20210701-081738](https://user-images.githubusercontent.com/1418289/124038716-efc18300-da44-11eb-8b6b-00b5be676820.jpg)

**Comment by Inlustra** [comment]
It does this already, the whole reason I built this project!

**Comment by Inlustra** [comment]
For the docker connector, you can use the label: dockerDash.link

Best bet is to read the docs for the connector you're using though

**Comment by petersem** [comment]
Sweet. will check it out.

**Comment by andlil** [comment]
> @Inlustra Can links be opened in a new window though? I couldn't find a mention of that.

+1 for new window.

**Comment by Inlustra** [comment]
Good shout! 

I think I might change the behaviour and have it open in a new window by default. Anyone against that?

**Comment by petersem** [comment]
@Inlustra this is the way

**Comment by Inlustra** [comment]
This has been changed in V4.0.0, clicking the item will by default open it in a new tab

**Comment by petersem** [comment]
Perfect!
