### ISSUE TITLE
enhancement: dark theme

### ISSUE THREAD

**Issue by petersem** [plugsy/core#19]
provide the option for a dark theme (quick! before i go blind) :)

**Comment by Inlustra** [comment]
The ability and an example Dark theme is available in V4.0.0
See theming:
https://github.com/plugsy/core/blob/main/docs/theming.md

**Comment by petersem** [comment]
@Inlustra Thanks. that's a nice feature.
[Slate](https://imgur.com/a/yNLi9bF)
