### ISSUE TITLE
Enhancement: Declare the agent in an enviromental variable, so it reduces the need for a config file.

### ISSUE THREAD

**Issue by ma-karai** [plugsy/core#26]
It would be great if one can utilize the agent function on remote hosts.

```
plugsy_agent: true
plugsy_server: IP or hostname and port
```

**Comment by Inlustra** [comment]
I think rather than do it this way, I'm going to have a separate Docker image that is only the agent and won't include any of the frontend at all.

**Comment by ma-karai** [comment]
makes sense, would also be much more light weight.

**Comment by Inlustra** [comment]
Solved in V6! 
https://github.com/plugsy/core/blob/main/docs/agent-mode.md
