### ISSUE TITLE
Support for ARMv7?

### ISSUE THREAD

**Issue by afonsosantos** [plugsy/core#3]
Hi!
Just discovered this project, and really like the look and feel of it!
Is there any chance this will be ported to ARM? Would like to run it on my Raspberry Pi 4.

Thanks!

**Comment by Inlustra** [comment]
I'd love to implement this, that being said I've never developed any docker images supporting ARMv7.

Do you know if it's just a case of replacing the FROM tag in docker to arm32v7/node? 
Would love some support or even just some direction.

**Comment by afonsosantos** [comment]
I've found this Docker image: [https://hub.docker.com/r/arm32v7/node/](https://hub.docker.com/r/arm32v7/node/), not sure if that "just works".
You could try to create a new branch for it and test. Sadly, I do not have much experience in Docker.

**Comment by petersem** [comment]
Using github actions
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

or just edit your build file and build manually for each architecture.

**Comment by Inlustra** [comment]
Yeah I'm actually working on this at the moment along with a Home Assistant supervisor integration

**Comment by afonsosantos** [comment]
Hi!

Nice, thank you for the follow-up.
I will test it and report!
