### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by samcro1967** [plugsy/core#36]
Love this project. Being able to manage settings directly from docker-compose with labels make life so much easier.  I had used Heimdall for quite a while now, but recently changed to Homer.  I really wish I was a coder and could help, but if you are looking for ideas on ways to extend this project in the future, I think homer could be a good place to draw inspiration from.

It is nice that you can create tabs, set icons for categories, set icons for individual apps, set a header, set a footer, control the colors for customization, control the number of columns, etc.  Icons can also be custom from a local file.  The downside is that everything is done in multiple config files.  Would be nice if you could control the main settings in one file and everything else with labels.

Amazing work here and look forward to where this goes in the future.

**Comment by Inlustra** [comment]
Thanks for the feedback! That's totally the intention actually!  Simple configuration via labels + a file to edit the more complicated bits (Such as themes etc)

The original intention was homer with some deeper integrations!

I also really like the idea of making this a startpage for my browser, so want to get some reader functionality in there too.

Unfortunately I'm renovating my house and my personal servers are all out of action until we've finished... as soon as we're done, I'll be jumping back on this. 

All feedback welcome for sure!
