### ISSUE TITLE
Possibility to use traefik label

### ISSUE THREAD

**Issue by mattthhdp** [plugsy/core#4]
It would be pretty awesome to be able to use the traefik label. Do you think this is something possible without too much hassle ?

**Comment by Inlustra** [comment]
Actually all of the labels required are configurable through environment variables already! (Though I haven't tested that side of it just yet)

```
export const environment = () => ({
  nameLabel: process.env.DOCKER_DASH_NAME_LABEL ?? "dockerDash.name",
  categoryLabel:
    process.env.DOCKER_DASH_CATEGORY_LABEL ?? "dockerDash.category",
  iconLabel: process.env.DOCKER_DASH_ICON_LABEL ?? "dockerDash.icon",
  linkLabel: process.env.DOCKER_DASH_LINK_LABEL ?? "dockerDash.link",
  parentsLabel: process.env.DOCKER_DASH_PARENTS_LABEL ?? "dockerDash.parents",
  dockerSocket: process.env.DOCKER_SOCKET ?? "/var/run/docker.sock",
  dockerHost: process.env.DOCKER_HOST,
  dockerPort: process.env.DOCKER_PORT,
  dockerProtocol: process.env.DOCKER_PROTOCOL as
    | "https"
    | "http"
    | "ssh"
    | undefined,
  dockerVersion: process.env.DOCKER_VERSION,
  fileStoragePath: process.env.DOCKER_DASH_FILE_STORAGE_PATH,
});
```

Feel free to launch the container with whatever you'd like the labels to be, I suppose in your case it would be to override the name label?

**Comment by mattthhdp** [comment]
Exactly, it would be easier to re-use the traefik label than recreate all of them
________________________________

**Comment by Inlustra** [comment]
That's already implemented, can you give it a try?

**Comment by mattthhdp** [comment]
As soon as I come back from work !
________________________________

**Comment by Inlustra** [comment]
It's worth mentioning that as of v2, these options are no longer configured using environment variables.
Instead you will have to use the config instead, an example config:

```
{
  "$schema": "https://github.com/Inlustra/auto-docker-dash/releases/download/v2.0.0/schema.json",
  "connectors": [
    {
      "type": "docker",
      "config": {
          "labelConfig": {
              "categoryLabel": "mycustomdockerlabel",
              "iconLabel": "mycustomdockerlabel",
              "linkLabel": "mycustomdockerlabel",
              "nameLabel": "mycustomdockerlabel",
              "parentsLabel": "mycustomdockerlabel"
          }
      }
    }
  ]
}

```

**Comment by Inlustra** [comment]
I'm going to close this, as the possibility to do such a thing does exist, if you have any other issues with this functionality, I'll re-open
