### ISSUE TITLE
Not all services are loading from docker labels after upgrade to 6.1.0

### ISSUE THREAD

**Issue by samcro1967** [plugsy/core#42]
I see the error below in the plugsy container logs after upgrading to 6.1.0.  Only about half of the icons appear on the page from docker labels.  Rolling back to V6.0.0 brings them all back.
```
today at 8:00:09 AMerror:   ┏ fail +3ms
today at 8:00:09 AMerror:   ┃ [1] Error: socket hang up
today at 8:00:09 AMerror:   ┃ [2]     at connResetException (internal/errors.js:639:14)
today at 8:00:09 AMerror:   ┃ [3]     at Socket.socketOnEnd (_http_client.js:499:23)
today at 8:00:09 AMerror:   ┃ [4]     at Socket.emit (events.js:412:35)
today at 8:00:09 AMerror:   ┃ [5]     at endReadableNT (internal/streams/readable.js:1334:12)
today at 8:00:09 AMerror:   ┃ [6]     at processTicksAndRejections (internal/process/task_queues.js:82:21)
today at 8:00:09 AMerror:   ┗ [7] { component: 'websiteConnection', id: 'WEBSITE', error: 'socket hang up' }
```

**Comment by Inlustra** [comment]
Apologies, I mistakenly pushed a breaking change in the latest release of Plugsy, it should be v7.0.0
For now, feel free to pin your version to 6.0.0

The reason you're not seeing icons: the default Plugsy labels have changed from `dockerDash.*` to `plugsy.*`
See the [docs](https://github.com/plugsy/core/blob/main/docs/connectors/docker.md)

I will look to re-release this as 7.0.0 as soon as I get some time

**Comment by samcro1967** [comment]
Switching to v7.0.0 and changing the labels has all of the services back.  Still seeing errors in the container log, but does not seem to be effecting anything.  Appreciate the quick response.
